### PR TITLE
confined logo to body width on mobile view with BS class

### PR DESCRIPTION
**Pull request by james-oldfield**
Site in mobile view

### CODE REVIEW

**Comment by nevosegal** [comment]
:+1: 

btw, is it terminal you're using there or something else? What theme is that?

**Comment by james-oldfield** [comment]
@nevosegal It's iterm :) Pretty much running off https://github.com/mathiasbynens/dotfiles/ 's dotfiles for the aesthetics

**Comment by nevosegal** [comment]
:) Thanks

**Comment by hughrawlinson** [comment]
3 Hugh points for @James-Oldfield!

**Pull request merged**
